#Constants
PASS = 'Pass'
FAIL = 'Fail'
NOT_EXECUTED = 'Not Executed'
TEST_SUCCESSFUL = 'Test Successful'
COMMAND_SUCCESS = 0

import subprocess


class Ios_franklin_Constants():
    launch_screen_ios = 'name == "Convatec me+ Companion™" AND label == "Convatec me+ Companion™" AND value == "Convatec me+ Companion™"'
    launch_screen_login_click = 'name == "Login"'
    login_screen_check = 'label == "Email"'
    login_screen_email = 'value == "Email" AND type == "XCUIElementTypeTextField"'
    login_screen_password = 'value == "Password" AND type == "XCUIElementTypeSecureTextField"'
    loginscreen = 'name == "Login"'
    login_screen_click_on_login = 'name == "LOGIN" AND label == "LOGIN" AND value == "LOGIN"'
    login_check = 'name == "Home" AND label == "Home" AND value == "Home"'
    launch='name == "Convatec me+ Companion™" AND label == "Convatec me+ Companion™" AND value == "Convatec me+ Companion™"'
    setted_goal = '357'
    set_goal='name == "dashrd-bt-setGoal"'
    enter_goal='name == "core-tf-unitsValue"'
    cancel_goal = 'name == "CANCEL" AND label == "CANCEL" AND value == "CANCEL"'
    set = 'label == "SET" AND name == "SET" AND value == "SET"'
    record_entry = 'label == "RECORD ENTRY" AND name == "RECORD ENTRY" AND value == "RECORD ENTRY"'
    catheter = '**/XCUIElementTypeTextField[`name == "core-tf-unitsValue"`][1]'
    naturally = '**/XCUIElementTypeTextField[`name == "core-tf-unitsValue"`][2]'
    tap = 'type == "XCUIElementTypeScrollView"'
    save = 'label == "SAVE" AND name == "SAVE" AND type == "XCUIElementTypeButton"'
    ok = 'label == "OK"'
    beverage = 'label == "Beverage" AND name == "Beverage" AND type == "XCUIElementTypeButton"'
    coffee = 'name == "hydRe-bt-tea"'
    alcohol = 'hydRe-bt-alcohol'
    water  = 'name == "hydRe-bt-small"'
    carbonated = 'hydRe-bt-bevearges'
    other = 'hydRe-bt-others'
    verify_entry = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-frthUnits"`][1]'
    beverage_save = 'name == "hydRe-bt-save"'
    plus='name == "plus_more"'
    input_water = 'value == "0" AND type == "XCUIElementTypeTextField"'
    void = 'name == "Urine Volume"'
    More = 'hydRe-bt-moreUnits'
    water_units = 'hydRe-tf-moreUnits'
    hide = 'How much did you drink?'
    Dashboard = 'name == "Menu"'
    user_dashboard = 'unselected_dashboard'
    dashboard1 = '**/XCUIElementTypeButton[`name == "Dashboard"`]'
    logout = 'name == "Logout" AND label == "Logout" AND value == "Logout"'
    summary = 'Summary'
    voided_data = '**/XCUIElementTypeOther[`name == "sumy-vw-cellLogs"`][1]'
    dropdown = 'name == "sumy-bt-dropDown"'
    dropdown1 = '**/XCUIElementTypeButton[`name == "Day"`]'
    dropdown_xpath = '**/XCUIElementTypeStaticText[`name == "Day"`]'
    week_dropdown = 'name == "sumy-lbl-timePeriod" AND label == "Week"'
    month_dropdown = 'name == "sumy-lbl-timePeriod" AND label == "Month"'
    ruf ='name == "Week"'
    # day_in_week = '**/XCUIElementTypeImage[`name == "sumy-bt-logDetails"`][1]'
    share = 'share'
    Invalid_PW = 'invalidpws'
    invalid_pw_classchain ='**/XCUIElementTypeStaticText[`name == "The provided access grant is invalid, expired, or revoked."`]'
    invalid_pwd = 'name == "Please enter a valid password"'
    API_OK = 'name == "OK"'
    day='name == "Day" AND label == "Day" AND value == "Day"'
    data ='**/XCUIElementTypeStaticText[`name == "200 ml"`][1]'
    custom_dropdown = 'name == "sumy-lbl-timePeriod" AND label == "Custom"'
    start_date = '**/XCUIElementTypeStaticText[`name == "Select Date"`][2]'
    date = '1'
    date_done ='core-bt-donePicker'
    end_date = 'name == "sumy-bt-endDate"'
    Apply = 'name == "sumy-bt-apply"'
    Indetail_day_in_custom  ='**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    total_data = 'rectangle_box'
    date1 = '2'
    user_name = 'name == "Log your beverage and urine"'
    menu = 'Menu'
    Menu_screen = 'name == "Menu" AND label == "Menu" AND value == "Menu"'
    me_plus = 'Me +'
    convatec_logo = 'convatec'
    dairy = 'Diary'
    # day_in_week = '**/XCUIElementTypeImage[`name == "sumy-bt-logDetails"`][1]'
    share = 'share'
    twohundred_inml = '**/XCUIElementTypeStaticText[`name == "200 ml"`][1]'
    alcohol = 'hydRe-bt-alcohol'
    sindhuja_UN = 'Sindhuja.Polnati@convatec.com'
    sindhuja_pw = 'Sindhuja@21'
    subhadra_UN = 'saisubhadra.abbineni@convateccom'
    subhadra_pw = 'AMMU@1218ask1'
    Invalid_UN = 'sindhuj@convateccom'
    error = 'Please enter a valid email'
    Invalid_PW = "User@23"
    invalid_pw_classchain = '**/XCUIElementTypeStaticText[`name == "The provided access grant is invalid, expired, or revoked."`]'
    invalid_pwd = 'name == "Please enter a valid password"'
    current_entry = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    entry = '**/XCUIElementTypeStaticText[`name == "200 ml"`][1]'
    entry_1 = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-frthUnits"`][1]'
    dailygoal_value = 'dashrd-bt-dailyGoalValue'
    percentage = 'dashrd-bt-percent'
    progress_bar = 'Progress'
    voided_volume_units = '**/XCUIElementTypeStaticText[`name == "oz"`][1]'
    voided_volume_intake_units = '**/XCUIElementTypeStaticText[`name == "oz"`][1]'
    track_urine_message = 'Log your beverage and urine'
    dairy_goal = 'Daily Goal'
    recordentry_1 = 'RECORD ENTRY'
    summary_default = 'name == "Scatter Chart. 2 datasets. Urine Voided, Beverage"'
    OZ = 'name == "oz" AND label == "oz" AND value == "1"'
    catheter_oz_check = '**/XCUIElementTypeStaticText[`name == "core-lbl-unitsValue"`][1]'
    ml_click = 'name == "ml"'
    ml_check = '**/XCUIElementTypeStaticText[`name == "core-lbl-unitsValue"`][1]'
    date_today = 'core-bt-date'
    current_time = 'core-bt-time'
    beverage_icon = '**/XCUIElementTypeButton[`name == "Beverage"`]'
    leak_icon = '**/XCUIElementTypeButton[`name == "Leak"`]'
    rec_entry = 'dashrd-bt-recordEntry'
    more_plus = 'hydRe-bt-moreUnits'
    taken_water = 'hydRe-tf-moreUnits'
    latest_input_water_record = 'name == "sumy-lbl-frthUnits" AND label == "250 ml"'
    default_urine_voided = '**/XCUIElementTypeButton[`name == "Urine"`]'
    beverage_record_entry1 = '**/XCUIElementTypeButton[`name == "Beverage"`]'
    beverage_name = 'Log your beverage type'
    set_goal_send_keys = 'core-tf-unitsValue'
    set_goal_key = 'name == "SET" AND label == "SET" AND type == "XCUIElementTypeButton"'
    set_goal_cancel_key = '**/XCUIElementTypeButton[`name == "CANCEL"`]'
    comment = 'Comments'
    sum_cath = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-sndUnits"`][1]'
    sum_nat = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-thrdUnits"`][1]'

    meplus_mobileno = 'me-bt-call'
    meplus_email = 'me-bt-mail'
    meplus_timings = 'Monday - Friday,'
    meplus_text1 = 'The me+™ program is designed to support you throughout all stages of your journey.'
    meplus_text2 = 'We have certified nurses and product specialists available to ensure you don’t have to figure it out alone. Ready for samples or want to speak to a member of the me+ support team.'
    meplus_menu_convatec = 'convatec'

    product_info_menu = 'name == "menu-lbl-title" AND label == "Product Info and Links"'
    faq_menu = 'name == "menu-lbl-title" AND label == "FAQs"'
    quick_links_menu = 'name == "menu-lbl-title" AND label == "Quick Links"'
    how_to_use ='name == "menu-lbl-title" AND label == "How to use?"'
    privacy_policy_menu = 'name == "menu-lbl-title" AND label == "Privacy Policy"'
    withdraw_consent_menu = 'name == "menu-lbl-title" AND label == "Withdraw Consent"'
    goal_menu = 'name == "menu-lbl-title" AND label == "Beverage Goal"'
    email_menu = 'name == "menu-lbl-userAge"'
    phone_menu = 'name == "menu-lbl-title" AND label == "1-800-422-8811"'
    logout_menu_classchain = '**/XCUIElementTypeStaticText[`name == "LOGOUT"`]'
    username_menu = 'name == "menu-lbl-userName"'
    user_email_menu = 'name == "menu-lbl-title" AND label == "Customersupport@convatec.com"'
    meplus_userprofile = '**/XCUIElementTypeButton[`name == "Me +"`]'
    meplus_userprofile_check = '**/XCUIElementTypeStaticText[`name == "me-lbl-value"`][1]'
    menu_userprofile_firstname = 'name == "me-lbl-title" AND label == "First Name"'
    menu_userprofile_secondname = 'name == "me-lbl-title" AND label == "Last Name"'
    menu_userprofile_email = 'name == "me-lbl-title" AND label == "Email"'
    menu_userprofile_contactnumber = 'name == "me-lbl-title" AND label == "Contact Number"'
    menu_userprofile_agerange = 'name == "me-lbl-title" AND label == "Contact Number"'
    menu_userprofile_gender = 'name == "me-lbl-title" AND label == "Gender"'
    menu_userprofile_password = 'name == "me-lbl-title" AND label == "Password"'
    menu_userprofile_delete = 'name == "userP_btn_deleteProfile"'
    menu_userprofile_update = 'name == "me-lbl-update"'
    menu_userprofile_edit = 'name == "userP_btn_edit"'
    menu_userprofile_back = 'name == "userP_btn_back"'
    leak_save_menu = 'name == "SAVE" AND label == "SAVE" AND type == "XCUIElementTypeButton"'
    daysummary_back = 'sumy-bt-backward'
    data_content = 'sumy-lbl-hdr-first'
    leak_date = 'core-bt-date'
    summary_first_select = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-thrdUnits"`][1]'
    summary_first_select_edit = 'sumyDay-bt-edit'
    summary_first_select_edit_nat = '**/XCUIElementTypeTextField[`name == "core-tf-unitsValue"`][2]'
    summary_first_select_edit_comment = 'Comments'
    summary_first_select_edit_comment_save_changes = 'name == "SAVE CHANGES" AND label == "SAVE CHANGES" AND type == "XCUIElementTypeButton"'
    summary_nat_ml = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-thrdUnits"`][1]'
    summary_cat_select = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-sndUnits"`][1]'
    summary_cat_select_edit_cat = '**/XCUIElementTypeTextField[`name == "core-tf-unitsValue"`][1]'
    summary_cat_select_select = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-sndUnits"`][1]'
    summary_edit_delete = 'sumyDay-bt-delete'
    summary_edit_date = 'sumyDay-lbl-date'
    summary_edit_void_cath = 'Voided Volume (Catheter)'
    summary_edit_void_nat = 'Voided Volume (Naturally)'
    summary_edit_void_comments = 'Comments'
    summary_edit_Date_Time = 'Date & Time'
    summary_edit_date_today = 'sumy-lbl-date'
    summary_edit_bavarage_save_change = 'name == "SAVE CHANGES" AND label == "SAVE CHANGES" AND type == "XCUIElementTypeButton"'
    summary_edit_beverage_medium = 'name == "hydRe-bt-medium"'
    summary_beverage_check = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-frthUnits"`][1]'
    summary_edit_save = 'hydRe-bt-save'
    register_yourself = 'name == "REGISTER YOURSELF" AND label == "REGISTER YOURSELF" AND type == "XCUIElementTypeButton"'
    provide_details = 'Provide your details'
    register_first_name = 'First Name'
    register_second_name = 'Last Name'
    register_mob_number = 'Contact Number'
    register_email = 'Email'
    register_email_verification = 'Verification link will sent to given email id.'
    register_user_first_name = 'value == "First name"'
    firstname_sendkeys = 'value == "John Cena"'
    register_user_second_name = 'value == "Last name"'
    lstname_sendkeys = 'value == "Bat"'
    register_user_mobnum = 'value == "+1 Contact number"'
    register_user_email = 'value == "Enter email"'
    reg_mailid = 'value == "naveen@yopmail.com"'
    register_checkbox1 = '**/XCUIElementTypeButton[`name == "uncheck"`][1]'
    register_checkbox2 = '**/XCUIElementTypeButton[`name == "uncheck"`][2]'


    # 12/3
    Share_symbol = 'name == "sumy-bt-share" AND label == "share"'
    Share_screen = 'Share Report for'
    Today = '**/XCUIElementTypeStaticText[`name == "Today"`]'
    week = '**/XCUIElementTypeStaticText[`name == "This Week"`]'
    month = '**/XCUIElementTypeStaticText[`name == "This Month"`]'
    custom = '**/XCUIElementTypeStaticText[`name == "Custom date range"`]'
    share_screen_confirmation = 'name == "YES" AND label == "YES" AND value == "YES"'
    sahre_screen_decline = '**/XCUIElementTypeStaticText[`name == "NO"`]'
    # 19/3
    convatec_logo_image = 'type == "XCUIElementTypeImage"'
    welcome_logo = "Welcome to"
    Franklin = 'name == "Convatec me+ Companion™" AND label == "Convatec me+ Companion™" AND value == "Convatec me+ Companion™"'
    Track = "A place to enter your beverages and urine "
    Register = '**/XCUIElementTypeButton[`name == "REGISTER YOURSELF"`]'
    login_button_launch = '**/XCUIElementTypeStaticText[`name == "Login"`]'
    contactus_text_launch = 'contactus_text_launch'
    email_text_login = 'Email'
    password_text_login = 'Password'
    Login = 'Login'
    fogot_text = '**/XCUIElementTypeStaticText[`name == "Forgot Password?"`]'
    register = '**/XCUIElementTypeStaticText[`name == "REGISTER YOURSELF"`]'
    registration_back = "regist-bt-back"
    provide_text_details = "Provide your details"
    firstname_text = 'First Name'
    lastname_text = 'Last Name'
    mobile_number_text = 'Contact Number'
    mobile_number_field = 'editPfl-tf-mobileNo'
    Email = 'Email'
    verification_text = 'Verification link will sent to given email id.'
    tandc_1 = '**/XCUIElementTypeButton[`name == "uncheck"`][1]'
    tandc_2 = '**/XCUIElementTypeButton[`name == "uncheck"`][2]'
    register_button_details = '**/XCUIElementTypeStaticText[`name == "REGISTER"`]'
    register_privacy = 'name == "regist-lbtermsAndCond"'
    register_privact_policy = 'name == "Privacy Notice" AND label == "Privacy Notice" AND value == "Privacy Notice"'
    register_termsandcond = 'name == "regist-lb-shareData"'
    register_termsa_conditions ='Terms of Use'
    register_terms_cond_accept ='name == "ACCEPT" AND label == "ACCEPT" AND type == "XCUIElementTypeButton"'
    register_1 = '**/XCUIElementTypeButton[`name == "REGISTER"`]'
    firstname_1 = 'Dave'
    secondname_2 = 'baut'
    mobile_num = '92929192'
    email_id = 'david@yopmail.com'
    register_done = 'Done'
    register_termsand_cond_back = 'Back'
    login_forgot_PW = '**/XCUIElementTypeStaticText[`name == "Forgot Password?"`]'
    login_forgot_PW_validation = 'Enter your email id'
    login_forgot_PW_email = 'value == "Enter email"'
    login_forgot_PW_email_send = 'value == "Enter email"'
    login_forgot_PW_enter_email = 'Enter your email id'
    password_reset_message = 'An email containing password reset link was sent to'
    login_forgot_PW_check_emailmessage = 'Please check your inbox.'
    password_checking_message = 'If you don’t receive an email in 15:00 m'
    login_forgot_PW_email_resend_message = 'name == "Resend" AND label == "Resend" AND value == "Resend"'
    login_forgot_pw_email_new = 'value == "Naveen@yopmail.com"'
    login_forgot_pw_email_sendbutton = 'name == "SEND" AND label == "SEND" AND type == "XCUIElementTypeButton"'
    login_forgot_pw_emailusername = 'name == "Naveen@yopmail.com"'
    register_Terms_cond = "Terms & Conditions Terms is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, Use Licenses It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,"
    register_mob_user = '**/XCUIElementTypeTextField[`value == "+1 Enter number"`]'
    goal_screen_menu = 'Set Daily Drinking Goal'
    goal_units_menu = 'core-lbl-unitsValue'
    goal_user_input_menu = 'core-tf-unitsValue'
    cancel_goal_menu = 'name == "CANCEL" AND label == "CANCEL" AND value == "CANCEL"'

    #25/3
    summary_dropdown = 'sumy-bt-dropDown'
    share_text ='name == "Share" AND label == "Share" AND value == "Share"'
    week_month_share_text = 'name == "sumy-bt-share" AND label == "share"'
    custom_start_date = 'sumy-bt-startDate'
    custom_end_date = 'sumy-bt-endDate'
    custom_dates_apply = 'sumy-bt-apply'

    check = 'name == "YES" AND label == "YES" AND type == "XCUIElementTypeButton"'
    date_ranges = "Select date range"

    # 3/4   code coverage beverage entry
    beverage_type = 'Log your beverage type'
    beverage_default_water = 'hydRe-bt-water'
    beverage_type_tea = 'Tea/Coffee'
    beverage_type_alchol = 'Alcohol'
    beverage_type_carbonated = 'Carbonated Beverages'
    # 4/4 product_info

    product_info_screen = 'Product Info and Resources'
    prdt_back_btn = 'menu_prdt_btn_back'
    top_catheter_training = '**/XCUIElementTypeStaticText[`name == "walkthrough-lb-title"`][1]'
    catheter_documment = 'walkthrough-lb-desc'
    catheter_first_learn = 'prdtInfo_bt_slide_learnMore'
    cather_convatec_link = '**/XCUIElementTypeImage[`name == "Convatec"`][1]'
    catheter_bottom = '**/XCUIElementTypeStaticText[`name == "walkthrough-lb-title"`][2]'
    catheter_second_learn = '**/XCUIElementTypeButton[`name == "prdtInfo_bt_learnMore"`][1]'
    meplus_support_text = 'name == "walkthrough-lb-title" AND label == "me+ Support and Resource Services"'
    meplus_learn_text = '**/XCUIElementTypeButton[`name == "prdtInfo_bt_learnMore"`][2]'
    meplus_learn_navigation = '**/XCUIElementTypeOther[`name == "me+™ Support & Services"`]'
    products = 'name == "walkthrough-lb-title" AND label == "Products and Services"'
    products_learn_text = '**/XCUIElementTypeButton[`name == "prdtInfo_bt_learnMore"`][3]'
    products_learn_navigation = 'name == "Home" AND label == "Home" AND value == "Home"'
    meplus_support_swipe = '**/XCUIElementTypeStaticText[`name == "walkthrough-lb-title"`][1]'
    meplus_top_learn_text = 'prdtInfo_bt_slide_learnMore'
    description = 'walkthrough-lb-desc'
    products_top_text = '**/XCUIElementTypeStaticText[`name == "walkthrough-lb-title"`][1]'
    products_top_learn_text = 'prdtInfo_bt_slide_learnMore'

    # faq
    faq_text_faq_screen = 'FAQs'
    faq_back_button = 'menu_faqs_btn_back'
    faq_search = 'Search'

    # 5/4
    search_catheter = 'name == "faq-lb-question" AND label == "Does Intermittent Self Catheterizing hurt?"'
    default_faq_qns ='name == "faq-lb-question" AND label == "What are the risks of ISC?"'
    faq_questions_dropdown = '**/XCUIElementTypeImage[`name == "faq-img-downArrow"`][1]'
    faq_question_description = 'name == "ISC devices mean catheterizing doesn’t have to interfere with your independence, your sexual relationships, or with living your life fully and in comfort."'
    privacy_policy_screen = 'Mobile App Privacy Notice'
    privacy_policy_back_button = 'temsAndcond-bt-back'
    privacy_policy_document = 'name == "Privacy Notice" AND label == "Privacy Notice" AND value == "Privacy Notice"'

    # 10/4
    how_to_use = 'name == "menu-lbl-title" AND label == "How to use?"'
    record = 'Record'
    record_entry_image = 'type == "XCUIElementTypeImage"'
    record_entry_description = 'name == "mwnu-walkthrough-lb-desc"'
    record_entry_next = 'name == "NEXT" AND label == "NEXT" AND value == "NEXT"'
    record_entry_skip = 'name == "Skip" AND label == "Skip" AND value == "Skip"'

    share_reports = 'Share Reports'
    share_reports_image = 'type == "XCUIElementTypeImage"'
    share_reports_description = 'name == "mwnu-walkthrough-lb-desc"'

    faq_product_info = 'View product info and FAQs'
    faq_product_info_image = 'type == "XCUIElementTypeImage"'
    faq_product_info_description = 'mwnu-walkthrough-lb-desc'
    faq_product_info_start = 'name == "START" AND label == "START" AND value == "START"'

    # 29/3
    mail_icon_menu = 'name == "menu-lbl-userAge"'
    default_set_menu = 'name == "SET" AND label == "SET" AND value == "SET"'

    # 1/4(withdraw)
    menu_setgoal_ml = 'name == "= 0 ml"'
    menu_setgoal_ml_value = 'name == "= 11829.40 ml"'
    withdraw_consent_screen = 'Withdraw Consent'
    withdraw_consent_back_screen = 'menu_consent_btn_back'
    improve_app = 'Improve the app'
    improve_app_button = 'menu-consent-swt-improveApp'
    marketing = 'Marketing Promotional'
    marketing_button = 'menu-consent-swt-marketingPromotion'
    improve_app_des = 'menu-consent-lb-shareData'
    improve_app_overall_content = 'name == "Marketing Consent"'
    menu_withdraw_save = 'menu-consent-bt-save'
    marketing_des = 'menu-consent-lb-receivePromotional'

    # 11/4
    edit_text_editscreen = 'name == "Edit" AND label == "Edit" AND value == "Edit"'
    edit_back_button = 'name == "Edit" AND label == "Edit" AND type == "XCUIElementTypeButton"'
    First_name_text = 'First Name'
    First_name_field = 'name == "editPfl-tf-firstName"'
    last_name_text = 'Last Name'
    mobile_number_text = 'Mobile Number'

    Age_field = 'editPfl-tf-age'
    edit_done_button = 'Done'
    edit_save = 'name == "Save" AND label == "Save" AND value == "Save"'

    # 12/4
    email_text_edit = 'Email'
    age_text_edit = 'Age'
    gender_text_edit = 'Gender'
    gender_dropdown = 'editPfl-tf-gender'
    male_text = 'name == "sumy-lbl-timePeriod" AND label == "MALE"'
    female_text = 'name == "sumy-lbl-timePeriod" AND label == "Female"'
    other_text = 'name == "sumy-lbl-timePeriod" AND label == "OTHER"'
    unknown_text = 'name == "sumy-lbl-timePeriod" AND label == "UNKNOWN"'
    edited_gender = 'name == "editPfl-tf-gender"'

    # 15/4
    update_menu = 'me-lbl-update'
    update_password = 'name == "Update Password" AND label == "Update Password" AND value == "Update Password"'
    update_back_button = 'name == "Update Password" AND label == "Update Password" AND type == "XCUIElementTypeButton"'
    old_password_text = 'Old Password'
    new_password_text = 'New Password'
    confirm_new_password_text = 'Confirm New Password'
    update_text = 'name == "UPDATE" AND label == "UPDATE" AND value == "UPDATE"'
    old_password_field = 'updatePwd-tf-oldPwd'
    new_password_field = 'updatePwd-tf-newPwd'
    confirm_new_password_field = 'updatePwd-tf-confirmNewPwd'

    delete_profile_text = 'DELETE PROFILE'
    delete_user_text = 'Delete User'
    delete_description = 'Are you sure, you want to delete your profile?'
    delete_cancel = 'name == "CANCEL" AND label == "CANCEL" AND value == "CANCEL"'
    delete_text_deletescreen = 'name == "DELETE" AND label == "DELETE" AND type == "XCUIElementTypeButton"'
    date_and_time = 'Date & Time'

    # 16/4
    delete_icon = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    leak_save = 'name == "SAVE" AND label == "SAVE" AND value == "SAVE"'
    leak_delete = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    day_in_week = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    delete_month = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    custom_delete = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'

    submit= 'name == "SUBMIT" AND label == "SUBMIT" AND value == "SUBMIT"'

    share_yes = 'name == "YES" AND label == "YES" AND value == "YES"'
    share_no = 'name == "NO" AND label == "NO" AND type == "XCUIElementTypeButton"'
    share_ask = '''**/XCUIElementTypeStaticText[`name == "YES,DON'T ASK AGAIN"`]'''
    third_part_verification = "FranklinAppReport"
    About_app ='name == "menu-lbl-title" AND label == "About Convatec me+ Companion™"'
    about_the_app ='About the App'
    about_backbtn = 'abtUs_btn_back'
    app_des ='name == "Convatec me+ Companion™" AND label == "Convatec me+ Companion™" AND value == "Convatec me+ Companion™"'
    app_disclaimer = 'Disclaimer'
    app_version='welcome-bt-version'

    valid_email ='Please enter a valid email'
    email_confirm = 'name == "Naveen@yopmail.com"'
    beverage_complete = '**/XCUIElementTypeStaticText[`name == "Completed"`][2]'
    home_date = 'dashrd-bt-dateNav'
    enter_in_comments = 'core-tv-comments'
    ok_button = 'OK'
    Totale_void_data = 'Total times (Natural + Catheter)'
    meplus_phn_call = 'call'
    meplus_email_send="cic@convatec.com "
    faq_searched_qn ='name == "faq-lb-question" AND label == "What are the benefits of Intermittent Self Catheterizing (ISC)?"'

    leak_Edit = 'sumy-Img-fifthLeak'
    
    
    Edit_screen_navigation='**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    leak_edit_symbol = 'sumyDay-bt-edit'
    edit_save_changes = '**/XCUIElementTypeStaticText[`name == "SAVE CHANGES"`]'
    edit_weeksummary = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    title_leak = '**/XCUIElementTypeStaticText[`name == "sumy-lbl-hdr-five"`][2]'
    leak_delete_icon = 'sumyDay-bt-delete'
    date_time_lable = 'sumyDay-lbl-date'
    Latest_month_top = '**/XCUIElementTypeButton[`name == "sumy-lbl-hdr-first"`][2]'
    leak_save_changes = 'name == "SAVE CHANGES" AND label == "SAVE CHANGES" AND value == "SAVE CHANGES"'
    leak_cancel = 'name == "CANCEL" AND label == "CANCEL" AND value == "CANCEL"'
    home = '**/XCUIElementTypeButton[`name == "Home"`]'

    urine_text = 'name == "Urine" AND label == "Urine" AND type == "XCUIElementTypeButton"'
    cathlogs_text = 'Cath Logs'
    catheter_count = 'rectangle_box'
    header_texts = 'Time'
    leak_success_toast = 'Leak logged successfully'

    urine_volume = 'Urine Volume'
    urine_oz_text = '**/XCUIElementTypeButton[`name == "oz"`]'
    urine_ml_text = 'name == "ml"'
    Urine_date_cancel_button = 'core-bt-cancelPicker'
    comments_input_field = 'core-tv-comments'
    total_beverage_volume = 'rectangle_box'

    week_indetail_logs = '**/XCUIElementTypeImage[`name == "sumy-Img-rightArrow"`][1]'
    Total_urine_data = 'Urine Vol'
    leak_note = 'Note: Leakage is any urine that involuntarily leaves your body in between times that you are using a catheter. You can record leak here.'
    leak_text = 'name == "Leak" AND label == "Leak" AND value == "Leak"'
    home_text_home = 'name == "Home" AND label == "Home" AND value == "Home"'
    Beverage_value = 'name == "Beverage" AND label == "Beverage" AND type == "XCUIElementTypeButton"'
    urine_delete_toast = 'Urine Deleted'
    leeak_delete_toast = 'Leak Deleted'
    dashboard_urine = 'name == "Urine"'

    version_in_menu = 'welcome-bt-version'
    password_field_profile = 'name == "me-lbl-value" AND label == "********"'
    version_launch = 'welcome-bt-version'
    contact_us_email = 'name == "sumy-lbl-timePeriod" AND label == "cic@convatec.com"'
    contact_us_number ='name == "sumy-lbl-timePeriod" AND label == "1-800-422-8811"'
    contact_us_in_login = 'Contact Us'
    Contact_number = 'Contact Number'
    version_login = 'login-bt-version'
    small_glass = 'small_glass'
    beverage_volume = 'Diary'

    share_logs = 'name == "menu-lbl-title" AND label == "Share Logs"'
    cancel_share_logs = 'name == "CANCEL" AND label == "CANCEL" AND value == "CANCEL"'
    share_logs_text_sharelogs_screen = 'name == "SHARE LOGS" AND label == "SHARE LOGS" AND value == "SHARE LOGS"'
    successful_share_logs = 'Logs uploaded successfully'
    share_logs_email_field = 'uploadLog-tf-email'

    consent_back_button = 'temsAndcond-bt-back'
    share_logs_login = 'name == "sumy-lbl-timePeriod" AND label == "Share Logs"'
    share_logs_screen_login = '**/XCUIElementTypeStaticText[`name == "Email"`][2]'
    share_logs_login_cancel_button = 'name == "CANCEL" AND label == "CANCEL" AND type == "XCUIElementTypeButton"'
    share_logs_share_button_login = 'name == "SHARE LOGS" AND label == "SHARE LOGS" AND type == "XCUIElementTypeButton"'



def get_device_id():
    cmd = "idevice_id -l"
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
    id = process.stdout.read().strip().decode()
    return id



def get_installed_apps():
    cmd = 'ideviceinstaller --list-apps'
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
    apps = process.stdout.read().strip().decode()
    return apps





