from alltestcases import *
import os

start_time = get_current_time()

serial_list = get_iOS_devices()
print(serial_list,"skjcada")

serial = serial_list
# serial = '00008130-001858402EF8001C'
# serial = '00008110-00145D19118B801E'
#serial = '00008101-00012CA62628801E' new
print("serial is ::", serial)
# cheks appium running or not
Appium_status = Checking_appium()

# Cheks whether franklin app is installed ir not
app_Installation_status = checking_app_installation(serial)

# Report Creation
workbook, sheet1 = create_workbook()
sheet2 = create_report_sheet(workbook)
path = "/Users/nadabala/Desktop/Reports/"
file_name = f"TR_Convatec_final_TC_{start_time.strftime('%d_%b_%Y_%H_%M_%S')}.xlsx"

print("generating report: report file name ", file_name)
# Declaring all functions in list_feature wise


testcases = [
        # registration::
        #
        # "verify_provide_text_register",
        # "verify_register_yourself",
        # "verify_get_back_register_launch",
        # "verify_first_name_text_register",
        # "verify_last_name_text_register",
        # "verify_mobile_text_register",
        # "verify_mobile_country_code_register",
        # "verify_email_text_register",
        # "verify_ver_link_text_register",
        # "verify_tc1_text_register",
        # "verify_tc2_text_register",
        # "verify_register_button_default_disable",
        # "verify_register_yourself_first_name",
        # "verify_register_yourself_last_name",
        # "verify_register_yourself_mobile_number",
        # "verify_register_yourself_email",
        # "verify_register_yourself_email_verification",
        # "verify_register_yourself_firstname",
        # "verify_register_yourself_secondname",
        # "verify_register_yourself_Mobilenumber",
        # "verify_register_yourself_screen",
        # "verify_register_yourself_details_provided_text",
        # "verify_register_yourself_first_name",
        # "verify_register_yourself_privacypolicy_check",
        # "verify_register_yourself_privacypolicy",
        # "verify_register_yourself_Termsandconditions_checkbox",
        # "verify_register_yourself_termsandcond",
        # "verify_register_yourself_check_privacypolicy",
        # "verify_register_yourself_check_termsandconditions",
        # "verify_register_yourself_back_button_termsandcond",
        # "verify_register_yourself_check_privacypolicy_navigation",
        # "verify_register_yourself_termas_cond_navigation",
        # "verify_back_arrow_email_confirmation",
        #
        # # #forgot screen::
        # #
        # "verify_forgot_password_text_login",
        # "verify_forgot_password",
        # "verify_forgot_password_check_email",
        # "verify_forgot_password_check_email_field",
        # "verify_password_link_text_email_confirmation",
        # "verify_forgot_password_check_send",
        # "verify_send_click_email_confirmation",
        # "verify_send_empty_fields",
        # "verify_send_invaild_email",
        # "verify_forgot_password_check_enteremail",
        # "verify_send_valid_registered_email",
        # "verify_text_email_verification_screen",
        # "verify_email_verification_screen",
        # "verify_time_email_verification_screen",
        # "verify_forgot_password_checkinboxmessage",
        # "verify_forgot_password_check_resendmessage",
        # "verify_forgot_password_checking_message",
        # "verify_forgot_password_checking_resetmessage",
        # #
        # #launch login screens
        # "verify_franklin_launch_screen",
        # "verify_franklin_login_screen",
        # "verify_convatec_logo_launch",
        # "verify_welcome_launch",
        # "verify_franklin_launch",
        # "verify_track_text_launch",
        # "verify_register_text_launch",
        # "verify_login_text_launch",
        # "verify_version_text_launch",
        # "verify_version_number_launch",
        # "verify_contact_us_text_launch",
        # "verify_share_logs_text_launch",
        #
        # "verify_click_share_logs_text_launch",
        # "verify_click_share_logs_email_text_launch",
        # "verify_click_share_logs_email_field_launch",
        # "verify_click_share_logs_cancel_button_launch",
        # "verify_click_share_logs_cancel_launch",
        # "verify_click_share_logs_share_logs_button_launch",
        # "verify_click_share_logs_error_share_logs_button_launch",
        # "verify_success_message_for_share_logs_launch",

        # "verify_click_contact_us_text_launch",
        # "verify_click_contact_us_email_launch",
        # "verify_click_contact_us_number_launch",
        # "verify_register_click_launch",
        # "verify_login_click_launch",
        # "verify_login_text_login",
        # "verify_email_text_login",
        # "verify_email_field_login",
        # "verify_password_text_login",
        # "verify_password_field_login",
        # "verify_login_button_login",
        # "verify_version_text_login",
        # "verify_contactus_text_login",
        # "verify_click_contact_us_text_login",
        # "verify_share_logs_text_login",
        # "verify_click_share_logs_text_login",
        # "verify_click_share_logs_email_text_login",
        # "verify_click_share_logs_email_field_login",
        # "verify_click_share_logs_cancel_button_login",
        # "verify_click_share_logs_cancel_login",
        # "verify_click_share_logs_share_logs_button_login",
        # "verify_click_share_logs_error_share_logs_button_login",
        # "verify_success_message_for_share_logs_login",
        # "verify_click_contact_us_email_login",
        # "verify_click_contact_us_number_login",
        # "verify_version_number_login",
        # "verify_login_click_launch",
        # "verify_franklin_login_iOS_Invalid_UN",
        # "verify_franklin_register_user_enter_Invalid_UN",
        # "verify_franklin_login_iOS_Invalid_PW",
        # "verify_franklin_register_user_enter_wrong_PW",
        # "verify_login_text_login_email_conf_screen",
        # "verify_email_text_login_email_conf_screen",
        # "verify_email_field_login_email_conf_screen",
        # "verify_submit_button_login_email_conf_screen",
        # "verify_version_text_login_email_conf_screen",
        # "verify_version_number_login_email_conf_screen",
        # "verify_contact_us_text_login_email_conf_screen",
        # "verify_franklin_login_iOS",
        # #
        # # ## set_goal::
        # #
        # "verify_set_hydration_goal_dashboard",
        # "verify_click_set_daily_goal_dashboard",
        # "verify_beverage_volume_dashboard",
        # "verify_current_date_dashboard",
        # "verify_existing_beverage_volume_dashboard",
        # "verify_set_goal_msg_dashboard",
        # "verify_set_daily_goal_dashboard",
        # "verify_void_number_dashboard",
        # "verify_void_volume_dashboard",
        # "verify_exit_goal_settings_screen",
        # "verify_set_enable_user_input_dashboard",
        # "verify_input_field_set_goal_dashboard",
        # "verify_set_text_daily_goal_dashboard",
        # "verify_set_button_default_daily_goal_dashboard",
        # "verify_cancel_goal_screen",
        # "verify_set_hydration_goal",
        # "verify_set_enable_selection_dashboard",
        # "verify_set_action_goal_creation_dashboard",
        # "verify_cancel_hydration_goal_settings_screen",
        # "verify_set_hydration_goal_by_user",
        # "verify_set_hydration_goal_by_five_digit_user",
        # "verify_set_hydration_goal_ml_equal_oz",
        # "verify_set_daily_goal_units_dashboard",
        # "verify_set_goal_oz_equal_ml_units",
        # "verify_set_hydration_goal_by_dashboard_selection",
        #
        # "verify_set_hydration_goal_random_value_menu",
        # "verify_set_hydration_goal_by_user_input_menu",
        # "verify_set_hydration_goal_on_selection_menu",
        # "verify_user_exit_without_goal_set_menu",
        # #
        # # #dashboard::and navigations
        # #
        # #
        # "verify_username_in_dashboard",
        # "verify_menu_dashboard",
        # "verify_dashboard_meplus",
        # "verify_dashboard_summary",
        # "verify_summary_dashboard",
        # "verify_meplus_dashboard",
        # "verify_dashboard_menu",
        # "verify_meplus_menu",
        # "verify_goal_value_dashboard",
        # "verify_precent_complete_dashboard",
        # "verify_progress_bar_dashboard",
        # "verify_goal_volume_units",
        # "verify_intake_volume_units",
        # "verify_track_msg_dashboard",
        # "verify_update_goal_value_dashboard",
        # "verify_set_goal_msg_dashboard",
        # "verify_set_goal_option_dashboard",
        # "verify_record_entry_option_dashboard",
        # #
        # # #record entries::
        # #
        # "verify_record_entry_urine_text",
        # "verify_record_entry_urine_date_And_time_text",
        # "verify_record_entry_urine_date_field",
        # "verify_record_entry_urine_clock_field",
        # "verify_record_entry_click_urine_date_field",
        # "verify_record_entry_urine_date_done_button",
        # "verify_record_entry_urine_date_cancel_button",
        # "verify_record_entry_urine_date_save_button",
        # "verify_record_entry_urine_click_date_done_button",
        # "verify_record_entry_urine_click_date_cancel_button",
        # "verify_record_entry_click_urine_clock_field",
        # "verify_record_entry_urine_clock_done_button",
        # "verify_record_entry_urine_clock_cancel_button",
        # "verify_record_entry_urine_clock_save_button",
        # "verify_record_entry_urine_click_clock_cancel_button",
        # "verify_record_entry_urine_volume_text",
        # "verify_record_entry_urine_ml_units_text",
        # "verify_record_entry_click_urine_ml_units_text",
        # "verify_record_entry_urine_oz_units_text",
        # "verify_record_entry_click_urine_oz_units_text",
        # "verify_record_entry_comments_text",
        # "verify_record_entry_comments_field",
        # "verify_record_entry_comments_enter_input_field",
        # "verify_total_beverage_volume_daysummary",
        # "verify_total_cathlogs_text_weeksummary",
        # "verify_total_cathlogs_count_weeksummary",
        # "verify_total_cathlogs_text_monthmmary",
        # "verify_total_cathlogs_count_monthsummary",
        # "verify_total_cathlogs_text_monthmmary",
        "verify_total_cathlogs_count_customsummary",
        # "verify_total_urine_vol_count_weeksummary",
        # "verify_total_urine_vol_text_weeksummary",
        # "verify_total_urine_vol_text_monthsummary",
        # "verify_total_urine_vol_count_monthsummary",
        "verify_total_urine_vol_count_customsummary",
        "verify_total_urine_vol_text_customsummary",
        # "verify_indetails_void_data_click_arrow_in_monthsummary",
        "verify_indetails_void_data_click_arrow_in_customsummary",
        # "verify_indetails_void_data_click_arrow_in_weeksummary",
        # "verify_headers_in_daysummary",
        # "verify_current_day_leak_record_entry_with_space_comment",
        # "verify_current_day_leak_record_entry_current_day_time",
        # "verify_note_leak_record_entry",
        # "verify_leak_in_leak_screen",
        # "verify_current_date_leak",
        # "verify_current_time_leak",
        # "verify_navigates_beverage_to_leak",
        # "verify_current_record_entry_catheter",
        # "verify_current_record_entry_naturally",
        # "verify_current_record_entry_both_naturally",
        # "verify_current_record_entry_catheter_without_comments",
        # "verify_current_record_entry_naturally_without_comments",
        # "verify_current_record_entry_both_without_comments",
        # "verify_urine_record_entry_both_without_comments",
        # "verify_urine_current_record_entry_both_without_comments",
        # "verify_save_text_record_entry",
        # "verify_comments_text_record_entry",
        # "verify_date_time_text_record_entry",
        # "verify_enter_text_record_entry",
        # "verify_enter_four_digit_record_entry_for_beverage",
        # "verify_indetails_beverage_data_in_customsummary",
        # "verify_indetails_beverage_data_in_weeksummary",
        # "verify_total_beverage_data_in_weeksummary",
        # "verify_record_entery_for_void",
        # "verify_record_entry_for_void_catheter",
        # "verify_record_entry_for_void_natural",
        # "verify_beverage_highlight_tea",
        # "verify_record_entry_for_beverage",
        # "verify_record_entry_for_beverage_water",
        # "verify_record_entry_for_beverage_input",
        # "verify_default_unit_selection_void_entry",
        # "verify_ml_oz_void_entry",
        # "verify_oz_ml_void_entry",
        # "verify_default_unit_oz_void_entry",
        # "verify_default_unit_ml_void_entry",
        # "verify_current_day_void_record_entry",
        # "verify_current_time_void_record_entry",
        # "verify_current_day_beverage_record_entry",
        # "verify_current_time_beverage_record_entry",
        # "verify_leak_title_record_entry",
        # "verify_date_time_heading_leak",
        # "verify_comments_heading_leak",
        # "verify_comments_input_text_leak",
        # "verify_save_text_leak",
        # "verify_current_day_leak_record_entry",
        # "verify_current_time_leak_record_entry",
        # "verify_void_record_entry",
        # "verify_beverage_record_entry",
        # "verify_leak_record_entry",
        #
        # #day_summmaries::
        # #
        # "verify_daysummary",
        # "verify_total_cathlogs_text_daysummary",
        # "verify_total_urine_vol_count_daysummary",
        # "verify_total_urine_vol_value_daysummary",
        # "verify_dairy_text_daysummary",
        #
        "verify_Day_summary_urine_currentdate",
        "verify_Day_summary_fluid_currentdate",
        # "verify_Day_summary_beverage_change_fluid",
        # "verify_week_summary_Ios_franklin",
        # "verify_urine_void_of_day_in_week_summary",
        # "verify_month_summary",
        # "verify_current_month_default_in_month_summary",
        # "verify_custom_summary",
        # "verify_creating_custom_summary",
        # "verify_restricts_end_custom_summary",
        #
        # #meplus::navigations
        #
        # "verify_me_plus_logo",
        # "verify_me_plus_phone_number",
        # "verify_me_plus_email",
        # "verify_me_plus_date_time",
        # "verify_me_plus_phone_number_call",
        # "verify_me_plus_email_send",
        # "verify_me_plus_text1",
        # "verify_me_plus_text2",
        # "verify_meplus_summary",
        # "verify_meplus_menu",
        # "verify_summary_meplus",
        # "verify_summary_menu",
        # "verify_menu_summary",
        # "verify_menu_meplus",
        # #
        # # #menu screens ::
        #
        # "verify_menu_text",
        # "verify_click_on_menu_text",
        # "verify_menu_icon",
        # "verify_navigate_symbol_profile_menu",
        # "verify_click_on_goal_tab_menu",
        # "verify_setgoal_on_goal_tab_menu",
        # "verify_setgoal_by_selection_menu",
        # "verify_setgoal_input_menu",
        # "verify_setgoal_cancel_text_menu",
        # "verify_setgoal_cancel_menu",
        #
        # "verify_product_info_tab_menu",
        # "verify_FAQs_tab_menu",
        # "verify_How_to_use_tab_menu",
        # "verify_Privacy_Policy_tab_menu",
        # "verify_withdraw_consent_tab_menu",
        # "verify_goal_tab_menu",
        # "verify_email_menu",
        # "verify_phone_menu",
        # "verify_logout_menu",
        # "verify_logout_app",
        # "verify_version_number_menu",
        # #
        # # #user_profile::
        #
        # "verify_username_menu",
        # "verify_user_email_menu",
        # "verify_navigates_userprofile_menu",
        # "verify_first_name_profile",
        # "verify_last_name_profile",
        # "verify_email_profile",
        # "verify_contact_profile",
        # "verify_age_profile",
        # "verify_gender_profile",
        # "verify_password_profile",
        # "verify_password_filed_user_profile",
        # "verify_update_password_profile",
        # "verify_delete_profile",
        # "verify_delete_week_profile",
        # "verify_delete_month_profile",
        # "verify_delete_custom_profile",
        # "verify_edit_profile",
        # "verify_edit_week_profile",
        # "verify_edit_month_profile",
        # "verify_edit_custom_profile",
        # "verify_navigate_profile_menu",
        #
        # # leak_entries & edit leak
        # "verify_record_entry_leak_current",
        # "verify_record_entry_leak_previous",
        # "verify_edit_leak_day_summary",
        # "verify_edit_leak_week_summary",
        # "verify_title_leak_details_day_summary",
        # "verify_delete_icon_leak_details_day_summary",
        # "verify_edit_icon_leak_details_day_summary",
        # "verify_date_time_heading_leak_details_day_summary",
        # "verify_date_time_heading_leak_details_day_summary",
        # "verify_date_time_value_leak_details_day_summary",
        # "verify_comments_heading_leak_details_day_summary",
        # "verify_comments_value_leak_details_day_summary",
        # "verify_leak_delete_day_summary",
        # "verify_title_leak_details_week_summary",
        # "verify_delete_icon_leak_details_week_summary",
        # "verify_edit_icon_leak_details_week_summary",
        # "verify_date_time_heading_leak_details_week_summary",
        # "verify_date_time_value_leak_details_week_summary",
        # "verify_comments_heading_leak_details_week_summary",
        # "verify_comments_value_leak_details_week_summary",
        # "verify_leak_delete_week_summary",
        # "verify_title_leak_details_month_summary",
        # "verify_delete_icon_leak_details_month_summary",
        # "verify_edit_icon_leak_details_month_summary",
        # "verify_date_time_heading_leak_details_month_summary",
        # "verify_date_time_value_leak_details_month_summary",
        # "verify_comments_heading_leak_details_month_summary",
        # "verify_comments_value_leak_details_month_summary",
        # "verify_leak_delete_month_summary",
        # "verify_title_leak_details_custom_summary",
        # "verify_delete_icon_leak_details_custom_summary",
        # "verify_edit_icon_leak_details_custom_summary",
        # "verify_date_time_heading_leak_details_custom_summary",
        # "verify_date_time_value_leak_details_custom_summary",
        # "verify_comments_heading_leak_details_custom_summary",
        # "verify_comments_value_leak_details_custom_summary",
        # "verify_leak_delete_custom_summary",
        # "verify_title_leak_edit_day_summary",
        # "verify_date_time_heading_leak_edit_day_summary",
        # "verify_comments_heading_leak_edit_day_summary",
        # "verify_comments_input_text_leak_edit_day_summary",
        # "verify_save_text_leak_edit_day_summary",
        # "verify_cancel_text_leak_edit_day_summary",
        # "verify_title_leak_edit_week_summary",
        # "verify_date_time_heading_leak_edit_week_summary",
        # "verify_comments_heading_leak_edit_week_summary",
        # "verify_comments_input_text_leak_edit_week_summary",
        # "verify_save_text_leak_edit_week_summary",
        # "verify_cancel_text_leak_edit_week_summary",
        # "verify_title_leak_edit_month_summary",
        # "verify_date_time_heading_leak_edit_month_summary",
        # "verify_comments_heading_leak_edit_month_summary",
        # "verify_comments_input_text_leak_edit_month_summary",
        # "verify_save_text_leak_edit_month_summary",
        # "verify_cancel_text_leak_edit_month_summary",
        # "verify_title_leak_edit_custom_summary",
        # "verify_date_and_time_heading_leak_details_custom_summary",
        # "verify_comments_heading_leak_edit_custom_summary",
        # "verify_comments_input_text_leak_edit_custom_summary",
        # "verify_save_text_leak_edit_custom_summary",
        # "verify_cancel_text_leak_edit_custom_summary",
        # "verify_record_entry_leak_future",
        # #
        # #void entries edit
        # "verify_record_entery_summary_natural_value_edit",
        "verify_void_catheter_value_edit",
        # "verify_void_edit_volume_catheter",
        # "verify_void_edit_volume_natural",
        # "verify_void_edit_volume_commets",
        # "verify_void_edit_volume_Date_Time",
        # "verify_void_edit_check_edit",
        # "verify_beverage_edit_catheter",
        #
        # #delete urine entry
        # "verify_record_entery_urine_void_delete_button",
        # "verify_record_entery_urine_void_date",
        # "verify_Delete_urine_entry_daysummary",
        # "verify_Delete_urine_entry_weeksummary",
        "verify_Delete_urine_entry_monthsummary",
        # "verify_Delete_urine_entry_customsummary",
        # "verify_Delete_icon_urine_naturally_entry_daysummary",
        # "verify_Delete_icon_urine_naturally_entry_weeksummary",
        # "verify_Delete_icon_urine_naturally_entry_monthsummary",
        # "verify_Delete_icon_urine_naturally_entry_customsummary",
        # "verify_Delete_icon_urine_catheter_entry_daysummary",
        # "verify_Delete_icon_urine_catheter_entry_weeksummary",
        # "verify_Delete_icon_urine_catheter_entry_monthsummary",
        # "verify_Delete_icon_urine_catheter_entry_customsummary",
        #
        #
        # # share in summaries::
        #
        # "verify_share_text_daysummary",
        # "verify_share_option_screen",
        # "verify_share_report_daysummary",
        # "verify_share_icon_daysummary",
        # "verify_Today_text_in_daysummary",
        # "verify_Week_text_in_daysummary",
        # "verify_month_text_in_daysummary",
        # "verify_custom_text_in_daysummary",
        # "verify_share_pdf_confirmation_screen",
        # "verify_share_pdf_custom_confirmation_screen",
        # "verify_cance_share_from_daysummary",
        # "verify_day_in_background_share_daysummary",
        # "verify_week_in_background_share_daysummary",
        # "verify_month_in_background_share_daysummary",
        # "verify_custom_in_background_share_daysummary",
        # "verify_click_share_yes_today_daysummary",
        # "verify_click_share_yes_disclaimer_today_daysummary",
        # "verify_click_share_no_today_daysummary",
        # "verify_click_share_yes_week_daysummary",
        # "verify_click_share_yes_disclaimer_week_daysummary",
        # "verify_click_share_no_week_daysummary",
        # "verify_click_share_yes_month_daysummary",
        # "verify_click_share_yes_disclaimer_month_daysummary",
        # "verify_click_share_no_month_daysummary",
        # "verify_click_share_yes_custom_daysummary",
        # "verify_click_share_no_custom_daysummary",
        # "verify_list_apps_share_yes_today_daysummary",
        # "verify_list_apps_share_yes_custom_daysummary",
        #
        # "verify_share_icon_weeksummary",
        # "verify_share_text_weeksummary",
        # "verify_share_report_weeksummary",
        # "verify_Today_text_in_weeksummary",
        # "verify_Week_text_in_weeksummary",
        # "verify_month_text_in_weeksummary",
        # "verify_custom_text_in_weeksummary",
        # "verify_custom_icon_in_weeksummary",
        # "verify_day_in_background_share_weeksummary",
        # "verify_week_in_background_share_weeksummary",
        # "verify_month_in_background_share_weeksummary",
        # "verify_custom_in_background_share_weeksummary",
        # "verify_click_share_yes_today_weeksummary",
        # "verify_click_share_yes_disclaimer_today_weeksummary",
        # "verify_click_share_no_today_weeksummary",
        # "verify_click_share_yes_week_weeksummary",
        # "verify_click_share_yes_disclaimer_week_weeksummary",
        # "verify_click_share_no_week_weeksummary",
        # "verify_click_share_yes_month_weeksummary",
        # "verify_click_share_yes_disclaimer_month_weeksummary",
        # "verify_click_share_no_month_weeksummary",
        # "verify_list_apps_share_yes_today_weeksummary",
        # "verify_list_apps_share_yes_custom_weeksummary",
        #
        # "verify_share_text_monthsummary",
        # "verify_share_icon_monthsummary",
        # "verify_Today_text_in_monthsummary",
        # "verify_week_text_in_monthsummary",
        # "verify_month_text_in_monthsummary",
        # "verify_custom_text_in_monthsummary",
        # "verify_share_report_monthsummary",
        # "verify_cance_share_from_monthsummary",
        # "verify_day_in_background_share_monthsummary",
        # "verify_week_in_background_share_monthsummary",
        # "verify_month_in_background_share_monthsummary",
        # "verify_custom_in_background_share_monthsummary",
        # "verify_click_share_yes_today_monthsummary",
        # "verify_click_share_yes_disclaimer_today_monthsummary",
        # "verify_click_share_no_today_monthsummary",
        # "verify_click_share_yes_week_monthsummary",
        # "verify_click_share_yes_disclaimer_week_monthsummary",
        # "verify_click_share_no_week_monthsummary",
        # "verify_click_share_yes_month_monthsummary",
        # "verify_click_share_yes_disclaimer_month_monthsummary",
        # "verify_click_share_no_month_monthsummary",
        # "verify_list_apps_share_yes_today_monthsummary",
        # "verify_list_apps_share_yes_custom_monthsummary",
        #
        # "verify_share_icon_customsummary",
        # "verify_share_text_customsummary",
        # "verify_share_report_customsummary",
        # "verify_Today_text_in_customsummary",
        # "verify_week_text_in_customsummary",
        # "verify_month_text_in_customsummary",
        # "verify_custom_text_in_customsummary",
        # "verify_day_in_background_share_customsummary",
        # "verify_week_in_background_share_customsummary",
        # "verify_month_in_background_share_customsummary",
        # "verify_custom_in_background_share_customsummary",
        # "verify_click_share_yes_today_customsummary",
        # "verify_click_share_yes_disclaimer_today_customsummary",
        # "verify_click_share_no_today_customsummary",
        # "verify_click_share_yes_week_customsummary",
        # "verify_click_share_yes_disclaimer_week_customsummary",
        # "verify_click_share_no_week_customsummary",
        # "verify_click_share_no_month_customsummary",
        # "verify_click_share_yes_month_customsummary",
        # "verify_list_apps_share_yes_today_customsummary",
        # "verify_list_apps_share_yes_custom_customsummary",
        #
        # # #menu::goal
        #
        # "verify_menu_in_menuscreen",
        # "verify_phone_icon_menu",
        # "verify_setgoal_default_set_from_menu",
        # "verify_navigation_setgoal_from_menu",
        # "verify_enable_set_by_selection_menu",
        # "verify_enable_set_by_input_menu",
        # "verify_oz_equivalent_ml_set_by_input_menu",
        # "verify_oz_equivalent_zero_ml_set_by_input_menu",
        # "verify_setdrinkinggoal_from_menu",
        # "verify_set_in_setgoal_from_menu",
        # "verify_input_box_in_setgoal_from_menu",
        # "verify_set_in_setgoal_from_menu",
        # "verify_enter_in_setgoal_from_menu",
        # "verify_setgoal_by_selection_equivalent_ml_menu",
        # "verify_default_oz_units_setgoal_from_menu",
        # "verify_predefined_oz_units_setgoal_from_menu",
        # "verify_predefined_goal_values_setgoal_from_menu",
        # #
        # # #withdraw consent ::
        # #
        # "verify_click_withdraw_consent",
        # "verify_withdraw_consent_text_withdraw_consent_screen",
        # "verify_back_arrow_withdraw_consent_screen",
        # "verify_click_back_arrow_withdraw_consent_screen",
        # "verify_improveapp_text_withdraw_consent_screen",
        # "verify_click_improveapp_withdraw_consent_screen",
        # "verify_improveapp_button_withdraw_consent_screen",
        # "verify_click_improveapp_button_withdraw_consent_screen",
        # "verify_click_improveapp_button_withdraw_consent_screen",
        # "verify_improveapp_des_withdraw_consent_screen",
        "verify_click_improveapp_des_withdraw_consent_screen",
        # "verify_click_improveapp_save_withdraw_consent_screen",
        # "verify_click_improveapp_and_save_withdraw_consent_screen",
        # "verify_save_withdraw_consent_screen",
        # "verify_marketing_text_withdraw_consent_screen",
        # "verify_click_marketing_withdraw_consent_screen",
        # "verify_marketing_button_withdraw_consent_screen",
        # "verify_click_marketing_button_withdraw_consent_screen",
        # "verify_marketing_des_withdraw_consent_screen",
        # "verify_click_marketing_des_withdraw_consent_screen",
        # "verify_click_marketing_save_withdraw_consent_screen",
        # "verify_click_marketing_and_save_withdraw_consent_screen",
        # #
        # # # record entry beverage screen ui::
        #
        # "verify_beverage_highlight_alcohol",
        # "verify_beverage_type_text",
        # "verify_beverage_type_select_other",
        # "verify_beverage_type_default_water",
        # "verify_beverage_type_select_tea",
        # "verify_beverage_type_select_alcohol",
        # "verify_beverage_type_select_carbonated",
        # "verify_beverage_type_water",
        # "verify_beverage_type_tea",
        # "verify_beverage_type_alcohol",
        # "verify_beverage_type_carbonated",
        # "verify_beverage_text_type_water",
        # "verify_beverage_highlight_carbonated",
        # "verify_beverage_highlight_other",
        # "verify_beverage_date_field",
        # "verify_beverage_current_field",
        # "verify_beverage_date_and_time_text",
        # "verify_beverage_calender_icon",
        # "verify_beverage_clock_icon",
        # #
        # # product info and links::
        # #
        # "verify_click_on_product_info_screen",
        # "verify_productinfo_text_in_product_info_screen",
        # "verify_backbutton_product_info_screen",
        # "verify_click_on_backbutton_product_info_screen",
        #
        # "verify_catheter_training_text_in_top_of_product_info_screen",
        # "verify_catheter_training_dcm",
        # "verify_catheter_training_top_learn",
        # "verify_click_catheter_training_top_learn",
        # "verify_catheter_training_text_in_bottom",
        # "verify_catheter_training_bottom_learn",
        # "verify_click_catheter_training_bottom_learn",
        # #
        # "verify_meplus_support_top_text",
        # "verify_meplus_support_top_description",
        # "verify_meplus_support_top_learn_text",
        # "verify_click_meplus_support_top_learn_text",
        # "verify_meplus_support_bottom_text",
        # "verify_meplus_support_bottom_learn_text",
        # "verify_click_meplus_support_bottom_learn_text",
        #
        # "verify_products_services_top_text",
        # "verify_products_services_top_description",
        # "verify_products_services_top_learn_text",
        # "verify_click_products_services_top_learn_text",
        # "verify_products_bottom_text",
        # "verify_products_bottom_learn_text",
        # "verify_click_products_bottom_learn_text",
        #
        # #About Franklin
        #
        # "verify_about_franklin_tab_menu",
        # "verify_about_franklin_arrow_menu",
        # "verify_clicks_about_franklin_tab_menu",
        # "verify_back_arrow_about_franklin",
        # "verify_title_about_franklin",
        # "verify_franklin_text_about_franklin",
        # "verify_franklin_content_about_franklin",
        # "verify_disclaimer_text_about_franklin",
        # "verify_disclaimer_content_about_franklin",
        # "verify_navigates_menu_back_arrow",
        #
        # # faqs:::
        #
        # "verify_click_FAQ_menu",
        # "verify_FAQ_text_FAQ_screen",
        # "verify_back_button_FAQ_screen",
        # "verify_click_back_button_FAQ_screen",
        # "verify_search_icon_FAQ_screen",
        # "verify_search_box_FAQ_screen",
        # "verify_search_content_faqs",
        # "verify_click_search_FAQ_screen",
        # "verify_faqs_search_intermittent_catheter",
        # "verify_search_by_words_FAQ_screen",
        # "verify_questions_in_FAQ_screen",
        # "verify_dropdown_for_questions_in_FAQ_screen",
        # "verify_search_related_FAQs",
        # "verify_left_arrow_image",
        # "verify_FAQ_text_menu",
        # "verify_search_content_FAQ_screen",
        # "verify_questions_format_in_FAQ_screen",
        # "verify_default_questions_in_FAQ_screen",
        # "verify_click_dropdown_for_questions_in_FAQ_screen",
        # "verify_click_back_button_FAQ_screen",
        #
        #
        # #privacy policy ::
        #
        # "verify_arrow_menu_privacy_policy",
        # "verify_click_on_privacy_policy",
        # "verify_back_button_privacy_policy",
        # "verify_click_back_button_privacy_policy",
        # "verify_scroll_privacy_policy",
        # "verify_privacy_policy_text_privacy_policy_screen",
        # "verify_document_privacy_policy",
        # "verify_content_privacy_policy",
        #
        #  # How to use   :::
        #
        # "verify_click_how_to_use",
        # "verify_record_text_how_to_use",
        # "verify_record_image_how_to_use",
        # "verify_record_entry_description_how_to_use",
        # "verify_record_entry_next_text",
        # "verify_click_record_entry_next_button",
        # "verify_record_entry_skip_text",
        # "verify_click_record_entry_skip_button",
        #
        # "verify_share_reports_text",
        # "verify_share_reports_walkthrough_image",
        # "verify_share_reports_walkthrough_description",
        # "verify_share_reports_next_text",
        # "verify_click_share_reports_next_button",
        # "verify_share_reports_skip_text",
        # "verify_click_share_reports_skip_button",
        #
        # "verify_product_info_and_faq_text",
        # "verify_product_info_and_faq_image",
        # "verify_product_info_and_faq_description",
        # "verify_product_info_and_faq_start_text",
        # "verify_click_product_info_and_faq_start_text",
        #
        # # Share logs::
        # "verify_menu_share_logs_text",
        # "verify_click_menu_share_logs_text",
        # "verify_click_menu_share_logs_text",
        # "verify_email_text_menu_share_logs",
        # "verify_share_logs_Email_field_share_logs",
        # "verify_cancel_text_menu_share_logs",
        # "verify_click_cancel_text_menu_share_logs",
        # "verify_share_logs_text_menu_share_logs",
        # "verify_click_share_logs_text_menu_share_logs",
        #
        # ##User edit profile ::::
        #
        # "verify_click_edit_profile",
        # "verify_back_button_edit_profile",
        # "verify_click_back_button_edit_profile",
        # "verify_click_save_with_invalid_data_edit_profile",
        # "verify_first_name_text_edit_profile",
        # "verify_edit_first_name_edit_profile",
        # "verify_edited_first_name_edit_profile",
        # "verify_last_name_text_edit_profile",
        # "verify_edit_last_name_edit_profile",
        # "verify_edited_last_name_edit_profile",
        # "verify_mobile_number_text_edit_profile",
        # "verify_edit_mobile_number_edit_profile",
        # "verify_edited_mobile_number_edit_profile",
        # "verify_email_text_edit_profile",
        # "verify_edit_email_edit_profile",
        # "verify_edited_email_edit_profile",
        # "verify_age_text_edit_profile",
        # "verify_edit_age_edit_profile",
        "verify_edited_age_edit_profile",
        # "verify_gender_text_edit_profile",
        # "verify_edit_gender_edit_profile",
        # "verify_edited_gender_edit_profile",
        # "verify_gender_dropdown_edit_profile",
        # "verify_male_text_dropdown_edit_profile",
        # "verify_click_male_text_dropdown_edit_profile",
        # "verify_female_text_dropdown_edit_profile",
        # "verify_click_female_text_dropdown_edit_profile",
        # "verify_other_text_dropdown_edit_profile",
        # "verify_click_other_text_dropdown_edit_profile",
        # "verify_unknown_text_dropdown_edit_profile",
        # "verify_click_unknown_text_dropdown_edit_profile",
        #
        # #Update password:::
        #
        # "verify_update_text",
        # "verify_update_password_text_update_screen",
        # "verify_back_button_update_screen",
        # "verify_click_back_button_update_screen",
        # "verify_old_password_text_update_screen",
        # "verify_new_password_text_update_screen",
        # "verify_new_password_text_update_screen",
        # "verify_confirm_new_password_text_update_screen",
        # "verify_old_password_field_update_screen",
        # "verify_new_password_field_update_screen",
        # "verify_confirm_new_password_field_update_screen",
        # "verify_update_text_update_screen",
        #
        # # Delete profile:::
        #
        # "verify_delete_text",
        # "verify_click_delete_text",
        # "verify_delete_description",
        # "verify_delete_cancel_text",
        # "verify_delete_click_cancel_text",
        # "verify_delete_delete_screen",
        # "verify_delete_user_delete_screen",
        # "verify_delete_confirmation_text",
        # "verify_delete_highlighted_delete_screen",
        #
        # ##Record entry leak delete::
        #
        # "verify_click_leak_Delete_day_summary",
        # "verify_leak_Delete_toast_day_summary",
        # "verify_click_leak_Delete_week_summary",
        # "verify_click_leak_Delete_month_summary",
        # "verify_click_leak_Delete_custom_summary",
        # #
        # "verify_click_beverage_Delete_day_summary",
        # "verify_click_beverage_Delete_week_summary",
        # "verify_click_beverage_Delete_month_summary",
        # "verify_click_beverage_Delete_custom_summary",
        # "verify_Delete_icon_beverage_day_summary",
        # "verify_Delete_icon_beverage_week_summary",
        # "verify_Delete_icon_beverage_month_summary",
        # "verify_Delete_icon_beverage_custom_summary"



]


# object declaration for the class
obj = franklin_ios_testcases(serial)

# function call
for func in testcases:
        func_call = getattr(obj, func)
        az_id,status, status_res = func_call()
        update_status(az_id, func, status, status_res, sheet2)

execution_data = get_execution_status(sheet2)
print(execution_data)
create_summary(sheet1, execution_data)

# report saving
test_report = os.path.join(path, file_name)
workbook.save(test_report)